swagger: '2.0'
info:
  version: 1.0.0
  title: MEAN3
  description: Api dla MEAN3
  contact:
    email: jarek.frydrych@gmail.com
basePath: /api
tags:
  - name: Security
    description: Endpointy dla modułu Security
  - name: Core
    description: Endpointy dla modułu Core
schemes:
  - http
  - https
paths:
  /security/login:
    x-swagger-router-controller: Security
    post:
      summary: Logowanie do aplikacji
      operationId: loginHandler
      tags:
        - Security
      parameters:
        - name: content
          description: Dane logowania użytkownika
          in: body
          required: true
          schema:
            $ref: '#/definitions/LoginParameters'
      responses:
        200:
          description: Zalogowano poprwanie
        403:
          description: Niepoprawne dane logowania
  /asd:
    x-swagger-router-controller: Core
    get:
      summary: Asd
      operationId: asdHandler
      tags:
        - Core
      responses:
        200:
          description: Asd response
definitions:
  LoginParameters:
    title: LoginParameters
    properties:
      username:
        title: Nazwa użytkownika
        type: string
      password:
        title: Hasło użytkownika
        type: string