swagger: '2.0'
info:
  version: 1.0.0
  title: MEANS
  description: Api dla MEANS
  contact:
    email: jarek.frydrych@gmail.com
basePath: /api
tags:
  - name: Security
    description: Endpointy dla modułu Security
  - name: Users
    description: Endpoity dla modułu Users
schemes:
  - http
  - https
paths:
  /security/login:
    x-swagger-router-controller: security
    x-swagger-router-no-firewall: true
    post:
      summary: Logowanie do aplikacji
      operationId: loginHandler
      tags:
        - Security
      parameters:
        - name: content
          description: Dane logowania użytkownika
          in: body
          required: true
          schema:
            $ref: '#/definitions/LoginParameters'
      responses:
        200:
          description: Zalogowano poprwanie
        403:
          description: Niepoprawne dane logowania
  /security/logout:
    x-swagger-router-controller: security
    get:
      summary: Wylogowanie z aplikacji
      operationId: logoutHandler
      tags:
        - Security
      responses:
        200:
          description: Poprawnie wylogowano użytkownika
  /security/current:
    x-swagger-router-controller: security
    get:
      summary: Pobieranie danych zalogowanego użytkownika
      operationId: currentUserQuery
      tags:
        - Security
      responses:
        200:
          description: Dane zalogowanego użytkownika
          schema:
            $ref: '#/definitions/CurrentUserView'
  /users:
    x-swagger-router-controller: users
    get:
      summary: Pobieranie listy userów
      operationId: usersListQuery
      tags:
        - Users
      parameters:
        - $ref: '#/parameters/page'
        - $ref: '#/parameters/count'
        - $ref: '#/parameters/sort_direction'
        - $ref: '#/parameters/sort_order'
      responses:
        200:
          description: Lista użytkowników
          schema:
            $ref: '#/definitions/UsersListView'
    post:
      summary: Tworzenie usera
      operationId: userNewHandler
      tags:
        - Users
      parameters:
        - name: content
          description: Dane usera
          in: body
          required: true
          schema:
            $ref: '#/definitions/UserNew'
      responses:
        200:
          description: Utworzono użytkownika
  /users/{id}:
    x-swagger-router-controller: users
    get:
      summary: Pobieranie wybranego użytkownika
      operationId: userDetailsQuery
      tags:
        - Users
      parameters:
        - name: id
          description: Identyfikator użytkownika
          type: string
          in: path
          required: true
      responses:
        200:
          description: Obiekt zawierający szczegóły użytkownika.
          schema:
            $ref: '#/definitions/UserDetailsView'
parameters:
  page:
    description: Numer aktualnie wyświetlanej strony
    name: page
    in: query
    type: integer
    default: 1
  count:
    description: Liczba rekordów wyświetlanych na stronie
    name: count
    in: query
    type: integer
    default: 25
  sort_direction:
    description: Kierunek sortowania (rosnąco, malejąco)
    name: sort_direction
    in: query
    type: string
  sort_order:
    description: Kolumna, według której nastąpi sortowanie danych
    name: sort_order
    in: query
    type: string
definitions:
  LoginParameters:
    title: LoginParameters
    properties:
      username:
        title: Nazwa użytkownika
        type: string
      password:
        title: Hasło użytkownika
        type: string
  UserNew:
    title: UserNew
    properties:
      username:
        title: Nazwa użytkownika
        type: string
      password:
        title: Hasło użytkownika
        type: string
  CurrentUserView:
    title: CurrentUserView
    properties:
      username:
        title: Nazwa użytkownika
        type: string
      firstname:
        title: Imię użytkownika
        type: string
      surname:
        title: Nazwisko użytkownika
        type: string
  UsersListView:
    title: UsersListView
    properties:
      total_count:
        title: Liczba rekordów
        type: integer
      data:
        title: Elementy listy
        type: array
        items:
          $ref: '#/definitions/UsersListItemView'
  UsersListItemView:
    title: UserListItemView
    properties:
      id:
        title: Identyfikator użytkownika
        type: string
      username:
        title: Nazwa użytkownika
        type: string
      firstname:
        title: Imię użytkownika
        type: string
      surname:
        title: Nazwisko użytkownika
        type: string
  UserDetailsView:
    title: UserDetailsView
    properties:
      username:
        title: Nazwa użytkownika
        type: string
      firstname:
        title: Imię użytkownika
        type: string
      surname:
        title: Nazwisko użytkownika
        type: string